"""model added

Revision ID: b85fa4a02d54
Revises: 2f371afbb561
Create Date: 2024-07-02 12:45:50.254659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85fa4a02d54'
down_revision = '2f371afbb561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
